### PR TITLE
fix: browe_project_files not useful

### PR DESCRIPTION
**Pull request by Leiyi548**
Telescope builtin browser_file is removed

### CODE REVIEW

**Comment by archite** [comment]
I find this a good bit easier:

```lua
local file_browser = require('telescope').load_extension('file_browser')
require('telescope.builtin').file_browser = file_browser.file_browser
```

**Comment by ahmedkhalf** [comment]
Since `file_browser` has been completely removed from Telescope, I think the best course of action right now, would be to completely remove the ctrl-b functionality from this plugin. (other suggestions are welcome)

**Comment by gegoune** [comment]
Perhaps it's possible to check if `nvim-telescope/telescope-file-browser.nvim` is installed and use it if so?

**Comment by gutyina70** [comment]
https://github.com/ahmedkhalf/project.nvim/issues/74

**Pull request closed without merging**
